"""
EvidencePhysio AI — Full Pipeline Runner
==========================================

Chains all 10 components together, end-to-end, using one sample patient.

Components 6, 8, and 9 use placeholder functions instead of real Claude
API calls (no available credit yet). Everything else runs for real.
"""

from app.models.patient import Patient
from app.components.patient_information_manager import PatientInformationManager
from app.components.missing_clinical_information_engine import MissingClinicalInformationEngine
from app.components.search_strategy_builder import SearchStrategyBuilder
from app.components.pubmed_retrieval_engine import PubMedRetrievalEngine
from app.components.evidence_prioritization_engine import EvidencePrioritizationEngine
from app.components.evidence_confidence_engine import EvidenceConfidenceEngine
from app.components.evidence_report_generator import EvidenceReportGenerator


# --------------------------------------------------------------------------- #
# Placeholders for Component 6, 8, 9 (Claude API calls)
# TODO: replace these with the real components once API credit is available.
# --------------------------------------------------------------------------- #

def placeholder_extraction(prioritized_evidence):
    """Stands in for Component 6 (ClaudeEvidenceExtractionEngine)."""
    validated_evidence = []
    for study in prioritized_evidence:
        combined = dict(study)
        combined["extracted_data"] = {
            "population": "Placeholder population",
            "intervention": "Placeholder intervention",
            "comparison": "Placeholder comparison",
            "outcome": "Placeholder outcome",
            "sample_size": "50",
            "study_design": study.get("publication_type", "randomized controlled trial"),
            "key_findings": "Placeholder key findings (Claude API not called).",
        }
        validated_evidence.append(combined)
    return {"validated_evidence": validated_evidence, "error_log": []}


def placeholder_synthesis(validated_evidence, patient, confidence_level):
    """Stands in for Component 8 (EvidenceSynthesisEngine)."""
    return (
        f"[PLACEHOLDER] Based on {len(validated_evidence)} stud(ies), evidence "
        f"relevant to this {patient.age}-year-old patient with "
        f"{patient.working_diagnosis} suggests further review is warranted. "
        f"(Claude API not called — confidence level: {confidence_level}.)"
    )


def placeholder_explanation(patient_specific_summary, confidence_level, confidence_explanation):
    """Stands in for Component 9 (NaturalLanguageExplanationEngine)."""
    return (
        f"[PLACEHOLDER] This explanation would normally be generated by Claude. "
        f"Confidence level is '{confidence_level}'. {confidence_explanation}"
    )


# --------------------------------------------------------------------------- #
# Sample raw patient input (as if it came from the UI)
# --------------------------------------------------------------------------- #

SAMPLE_RAW_DATA = {
    "working_diagnosis": "Rotator Cuff Tendinopathy",
    "age": 47,
    "sex": "Female",
    "occupation": "Teacher",
    "dominant_side": "Right",
    "activity_level": "Moderate",
    "onset": "Insidious",
    "duration": "6 weeks",
    "mechanism_of_injury": "",
    "stage_of_healing": "",
    "pain_severity": 7,
    "pain_irritability": "High",
    "pain_type": "",
    "pain_location": "Lateral shoulder",
    "pain_behavior": "",
    "symptoms": ["Night pain"],
    "past_medical_history": [],
    "past_surgical_history": [],
    "comorbidities": [],
    "medications": ["NSAIDs"],
    "imaging": [],
    "baseline_function": "",
    "functional_limitations": ["Cannot lift arm above shoulder"],
    "outcome_measures": [],
    "active_rom": "",
    "passive_rom": "",
    "strength": "",
    "special_tests": [],
    "neuro_screen": "",
    "movement_analysis": "",
    "patient_goals": ["Return to swimming"],
    "fear_avoidance": False,
    "occupational_demands": "",
    "yellow_flags": [],
    "visit_frequency": "",
    "equipment_access": "",
    "compliance_history": "",
}


def run_pipeline():
    print(">>> Component 1: Patient Information Manager")
    manager = PatientInformationManager()
    patient = manager.process(SAMPLE_RAW_DATA)
    print("    Patient profile created.\n")

    print(">>> Component 2: Missing Clinical Information Engine")
    missing_info_engine = MissingClinicalInformationEngine()
    patient_context = missing_info_engine.process(patient)
    print(f"    Status: {patient_context['status']}, Missing: {patient_context['missing_fields']}\n")

    print(">>> Component 3: Search Strategy Builder")
    strategy_builder = SearchStrategyBuilder()
    query = strategy_builder.process(patient_context)
    print(f"    Query: {query}\n")

    print(">>> Component 4: PubMed Retrieval Engine")
    retrieval_engine = PubMedRetrievalEngine()
    retrieval_result = retrieval_engine.process(query, max_results=10)
    retrieved_evidence = retrieval_result["retrieved_evidence"]
    print(f"    Retrieved {len(retrieved_evidence)} article(s). Needs expansion: {retrieval_result['needs_expansion']}\n")

    print(">>> Component 5: Evidence Prioritization Engine")
    prioritization_engine = EvidencePrioritizationEngine()
    prioritization_result = prioritization_engine.process(retrieved_evidence)
    prioritized_evidence = prioritization_result["prioritized_evidence"]
    print(f"    Prioritized {len(prioritized_evidence)} article(s). Limited: {prioritization_result['limited_evidence']}\n")

    # If PubMed returned nothing real (query too narrow), fall back to a
    # sample study so the rest of the pipeline can still be demonstrated.
    if not prioritized_evidence:
        print("    No real articles retrieved — using a fallback sample study to continue the demo.\n")
        prioritized_evidence = [{
            "pmid": "9999999",
            "title": "Effectiveness of eccentric exercise for rotator cuff tendinopathy",
            "authors": ["Jane Smith", "John Doe"],
            "journal": "Journal of Physiotherapy",
            "publication_year": "2022",
            "doi": "10.1000/example.doi",
            "publication_type": "randomized controlled trial",
            "relevance_score": 6,
        }]

    print(">>> Component 6: Claude Evidence Extraction Engine [PLACEHOLDER]")
    extraction_result = placeholder_extraction(prioritized_evidence)
    validated_evidence = extraction_result["validated_evidence"]
    print(f"    Validated {len(validated_evidence)} article(s).\n")

    print(">>> Component 7: Evidence Confidence Engine")
    confidence_engine = EvidenceConfidenceEngine()
    confidence_result = confidence_engine.process(validated_evidence)
    print(f"    Confidence: {confidence_result['confidence_level']}\n")

    print(">>> Component 8: Evidence Synthesis Engine [PLACEHOLDER]")
    patient_specific_summary = placeholder_synthesis(
        validated_evidence, patient, confidence_result["confidence_level"]
    )
    print(f"    Summary: {patient_specific_summary}\n")

    print(">>> Component 9: Natural Language Explanation Engine [PLACEHOLDER]")
    natural_language_explanation = placeholder_explanation(
        patient_specific_summary,
        confidence_result["confidence_level"],
        confidence_result["explanation"],
    )
    print(f"    Explanation: {natural_language_explanation}\n")

    print(">>> Component 10: Evidence Report Generator")
    report_generator = EvidenceReportGenerator()
    final_result = report_generator.process(
        patient=patient,
        query=query,
        prioritized_evidence=prioritized_evidence,
        validated_evidence=validated_evidence,
        confidence_result=confidence_result,
        patient_specific_summary=patient_specific_summary,
        natural_language_explanation=natural_language_explanation,
    )

    print("\n" + "=" * 60)
    print("FULL PIPELINE COMPLETED SUCCESSFULLY")
    print("=" * 60 + "\n")
    print(final_result["human_readable_report"])


if __name__ == "__main__":
    run_pipeline()