"""
EvidencePhysio AI — Streamlit Interface
==========================================

A simple web UI for entering patient data and viewing the generated
evidence report, built on top of the existing 10-component pipeline.
"""

import streamlit as st

from app.models.patient import Patient
from app.components.patient_information_manager import PatientInformationManager
from app.components.missing_clinical_information_engine import MissingClinicalInformationEngine
from app.components.search_strategy_builder import SearchStrategyBuilder
from app.components.pubmed_retrieval_engine import PubMedRetrievalEngine
from app.components.evidence_prioritization_engine import EvidencePrioritizationEngine
from app.components.evidence_confidence_engine import EvidenceConfidenceEngine
from app.components.evidence_report_generator import EvidenceReportGenerator


# --------------------------------------------------------------------------- #
# Placeholders for Components 6, 8, 9 (same as main.py, until API credit
# is available)
# --------------------------------------------------------------------------- #

def placeholder_extraction(prioritized_evidence):
    validated_evidence = []
    for study in prioritized_evidence:
        combined = dict(study)
        combined["extracted_data"] = {
            "population": "Placeholder population",
            "intervention": "Placeholder intervention",
            "comparison": "Placeholder comparison",
            "outcome": "Placeholder outcome",
            "sample_size": "50",
            "study_design": study.get("publication_type", "randomized controlled trial"),
            "key_findings": "Placeholder key findings (Claude API not called).",
        }
        validated_evidence.append(combined)
    return validated_evidence


def placeholder_synthesis(validated_evidence, patient, confidence_level):
    return (
        f"[PLACEHOLDER] Based on {len(validated_evidence)} stud(ies), evidence "
        f"relevant to this {patient.age}-year-old patient with "
        f"{patient.working_diagnosis} suggests further review is warranted. "
        f"(Claude API not called — confidence level: {confidence_level}.)"
    )


def placeholder_explanation(confidence_level, confidence_explanation):
    return (
        f"[PLACEHOLDER] This explanation would normally be generated by Claude. "
        f"Confidence level is '{confidence_level}'. {confidence_explanation}"
    )


# --------------------------------------------------------------------------- #
# Page setup
# --------------------------------------------------------------------------- #

st.set_page_config(page_title="EvidencePhysio AI", page_icon="🩺", layout="centered")

st.title("🩺 EvidencePhysio AI")
st.caption("AI-assisted evidence retrieval for physiotherapy clinical decisions")

st.markdown(
    "Enter a patient's clinical profile below. The system does **not** diagnose — "
    "it retrieves and summarizes published evidence to support treatment planning."
)

# --------------------------------------------------------------------------- #
# Input form
# --------------------------------------------------------------------------- #

with st.form("patient_form"):
    st.subheader("Patient Information")

    col1, col2 = st.columns(2)
    with col1:
        working_diagnosis = st.text_input("Working diagnosis", "Rotator Cuff Tendinopathy")
        age = st.number_input("Age", min_value=0, max_value=120, value=47)
        sex = st.selectbox("Sex", ["female", "male", "other"])
        pain_severity = st.slider("Pain severity (NRS, 0-10)", 0, 10, 7)

    with col2:
        occupation = st.text_input("Occupation", "Teacher")
        dominant_side = st.selectbox("Dominant side", ["Right", "Left"])
        activity_level = st.selectbox("Activity level", ["Low", "Moderate", "High"])
        onset = st.text_input("Onset", "Insidious")

    functional_limitations = st.text_area(
        "Functional limitations (one per line)",
        "Cannot lift arm above shoulder",
    )
    patient_goals = st.text_area(
        "Patient goals (one per line)",
        "Return to swimming",
    )

    submitted = st.form_submit_button("Generate Evidence Report")


# --------------------------------------------------------------------------- #
# Pipeline execution
# --------------------------------------------------------------------------- #

if submitted:
    raw_data = {
        "working_diagnosis": working_diagnosis,
        "age": int(age),
        "sex": sex,
        "occupation": occupation,
        "dominant_side": dominant_side,
        "activity_level": activity_level,
        "onset": onset,
        "duration": "",
        "mechanism_of_injury": "",
        "stage_of_healing": "",
        "pain_severity": int(pain_severity),
        "pain_irritability": "",
        "pain_type": "",
        "pain_location": "",
        "pain_behavior": "",
        "symptoms": [],
        "past_medical_history": [],
        "past_surgical_history": [],
        "comorbidities": [],
        "medications": [],
        "imaging": [],
        "baseline_function": "",
        "functional_limitations": [
            line.strip() for line in functional_limitations.split("\n") if line.strip()
        ],
        "outcome_measures": [],
        "active_rom": "",
        "passive_rom": "",
        "strength": "",
        "special_tests": [],
        "neuro_screen": "",
        "movement_analysis": "",
        "patient_goals": [
            line.strip() for line in patient_goals.split("\n") if line.strip()
        ],
        "fear_avoidance": False,
        "occupational_demands": "",
        "yellow_flags": [],
        "visit_frequency": "",
        "equipment_access": "",
        "compliance_history": "",
    }

    with st.spinner("Running the evidence pipeline..."):
        try:
            manager = PatientInformationManager()
            patient = manager.process(raw_data)

            missing_info_engine = MissingClinicalInformationEngine()
            patient_context = missing_info_engine.process(patient)

            strategy_builder = SearchStrategyBuilder()
            query = strategy_builder.process(patient_context)

            retrieval_engine = PubMedRetrievalEngine()
            retrieval_result = retrieval_engine.process(query, max_results=10)
            retrieved_evidence = retrieval_result["retrieved_evidence"]

            prioritization_engine = EvidencePrioritizationEngine()
            prioritization_result = prioritization_engine.process(retrieved_evidence)
            prioritized_evidence = prioritization_result["prioritized_evidence"]

            used_fallback = False
            if not prioritized_evidence:
                used_fallback = True
                prioritized_evidence = [{
                    "pmid": "9999999",
                    "title": "Effectiveness of eccentric exercise for rotator cuff tendinopathy",
                    "authors": ["Jane Smith", "John Doe"],
                    "journal": "Journal of Physiotherapy",
                    "publication_year": "2022",
                    "doi": "10.1000/example.doi",
                    "publication_type": "randomized controlled trial",
                    "relevance_score": 6,
                }]

            validated_evidence = placeholder_extraction(prioritized_evidence)

            confidence_engine = EvidenceConfidenceEngine()
            confidence_result = confidence_engine.process(validated_evidence)

            patient_specific_summary = placeholder_synthesis(
                validated_evidence, patient, confidence_result["confidence_level"]
            )
            natural_language_explanation = placeholder_explanation(
                confidence_result["confidence_level"], confidence_result["explanation"]
            )

            report_generator = EvidenceReportGenerator()
            final_result = report_generator.process(
                patient=patient,
                query=query,
                prioritized_evidence=prioritized_evidence,
                validated_evidence=validated_evidence,
                confidence_result=confidence_result,
                patient_specific_summary=patient_specific_summary,
                natural_language_explanation=natural_language_explanation,
            )

        except Exception as e:
            st.error(f"Something went wrong: {e}")
            st.stop()

    # ----------------------------------------------------------------- #
    # Display results
    # ----------------------------------------------------------------- #

    st.success("Report generated successfully!")

    if used_fallback:
        st.info(
            "No live PubMed results matched this query, so a sample study is "
            "shown below to demonstrate the full pipeline."
        )

    st.subheader("📋 Search Strategy")
    st.code(query, language="text")

    st.subheader("📚 Selected Studies")
    for study in prioritized_evidence:
        st.markdown(
            f"**{study['title']}**  \n"
            f"{study['journal']} ({study['publication_year']}) — score: {study['relevance_score']}"
        )

    st.subheader("📊 Evidence Confidence")
    st.metric("Confidence Level", confidence_result["confidence_level"].title())
    st.caption(confidence_result["explanation"])

    st.subheader("🧾 Patient-Specific Summary")
    st.write(patient_specific_summary)

    st.subheader("💬 Natural Language Explanation")
    st.write(natural_language_explanation)

    st.subheader("📥 Full Report")
    st.text_area("Human-readable report", final_result["human_readable_report"], height=300)
    st.download_button(
        "Download JSON Report",
        data=final_result["json_report"],
        file_name="evidence_report.json",
        mime="application/json",
    )